// <auto-generated />
using System;
using ApiProject_Joachim_Adomako.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProject_Joachim_Adomako.Migrations
{
    [DbContext(typeof(SportDbContext))]
    [Migration("20241224125739_secondMigration")]
    partial class secondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiProject_Joachim_Adomako.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Date");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Image");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Location");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Outcome");

                    b.Property<string>("Team1_id")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Team Id 1");

                    b.Property<string>("Team2_id")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Team Id 2");

                    b.HasKey("Id");

                    b.HasIndex("Team1_id");

                    b.HasIndex("Team2_id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ApiProject_Joachim_Adomako.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age Player");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Picture Player");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Name Player");

                    b.Property<int>("Team_id")
                        .HasColumnType("int")
                        .HasColumnName("Team Id");

                    b.HasKey("Id");

                    b.HasIndex("Team_id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("ApiProject_Joachim_Adomako.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("City Team");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name Coach");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Image Team");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Name Team");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Sport Team");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ApiProject_Joachim_Adomako.Models.Match", b =>
                {
                    b.HasOne("ApiProject_Joachim_Adomako.Models.Team", "Team1")
                        .WithMany("HomeMatches")
                        .HasForeignKey("Team1_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiProject_Joachim_Adomako.Models.Team", "Team2")
                        .WithMany("AwayMatches")
                        .HasForeignKey("Team2_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("ApiProject_Joachim_Adomako.Models.Player", b =>
                {
                    b.HasOne("ApiProject_Joachim_Adomako.Models.Team", "Team")
                        .WithMany("players")
                        .HasForeignKey("Team_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ApiProject_Joachim_Adomako.Models.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("players");
                });
#pragma warning restore 612, 618
        }
    }
}
